### ISSUE TITLE
Use anyOf instead oneOf for nullable fields

### ISSUE THREAD

**Issue by lzap** [invopop/jsonschema#162]
Hello, the generator currently creates this schema for nullable fields:

```yaml
---
"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://github.com/osbuild/blueprint-schema/account
type: object
properties:
  groups:
    oneOf:
    - description: Operating system group accounts to be created on the image.
      type: array
      items:
        "$ref": "https://github.com/osbuild/blueprint-schema/account_group"
    - type: 'null'
```

While there is nothing wrong with `oneOf`, a validator must perform complete check of the other branch because that is essentially an exclusive OR operation. Using `anyOf` will do the same job but validation will be faster.

Cheers.
